### PR TITLE
fix: `matchCosmeticFilters` should report generic hide exceptions

### LINKED ISSUE #5229: Cosmetic filters: generichide exceptions should be returned from matching
Filters like `@@||github.io^$generichide` prevent generic cosmetic filters from being matched. But because those are technically network filters, currently those are not returned on the list of matched filters/exceptions. This is done also for performance reasons, if we don't want to hide anything, we should  not match any cosmetic filters. 

For sake of logging, we could return `generichide` exceptions from `matchCosmeticFilters` which out "hide" filters being mentioned specifically.

### PR DESCRIPTION
**Pull request by seia-soto**
fixes #5229

- Extends return type `matches` to include `NetworkFilter` as generic hide exception is a "network filter".
- Changes return type of `shouldApplyHideException` to `NetworkFilter` or `undefined` to comply with flow of `matchCosmeticFilters`.

### CODE REVIEW

File: packages/adblocker/src/engine/engine.ts [hunk 1]
```diff
@@ -1174,16 +1178,32 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
...
+    matches: (
+      | {
+          filter: CosmeticFilter | undefined;
+          exception: CosmeticFilter | undefined;
+        }
+      | {
+          filter: undefined;
+          exception: NetworkFilter | undefined;
+        }
+    )[];
```
Comment (seia-soto) [inline packages/adblocker/src/engine/engine.ts:1190]: This change is not backward compatible but suggested as we cannot bring all filters: see https://github.com/ghostery/adblocker/issues/5229#issuecomment-3371772383.

File: packages/adblocker/test/engine/engine.test.ts [hunk 2]
```diff
@@ -1814,6 +1814,23 @@ foo.com###selector
     );
   });
 
+  describe('#matchCosmeticFilters', () => {
+    it('reports generic hide exceptions', () => {
+      const engine = FilterEngine.parse('###ad\n@@||foo.com^$generichide');
```
Comment (chrmod) [inline packages/adblocker/test/engine/engine.test.ts]: please split lines for readability

File: packages/adblocker/test/engine/engine.test.ts [hunk 3]
```diff
@@ -1814,6 +1814,23 @@ foo.com###selector
...
+      const { matches } = engine.matchCosmeticFilters({
+        url: 'https://foo.com',
+        hostname: 'foo.com',
+        domain: 'foo.com',
+        classes: ['ad'],
+        getRulesFromDOM: true,
+      });
+      expect(matches.length).to.be.eql(1);
+      expect(matches[0].exception?.isNetworkFilter()).to.be.true;
```
Comment (chrmod) [inline packages/adblocker/test/engine/engine.test.ts]: lets have `const match = matches[0]!`; so later we don't need to use `!` or `?`.

Also, lets verify that `filter` is empty

File: packages/adblocker/test/engine/engine.test.ts [hunk 4]
```diff
@@ -1814,6 +1814,23 @@ foo.com###selector
...
+      expect(matches[0].exception!.isGenericHide()).to.be.true;
```
Comment (chrmod) [inline packages/adblocker/test/engine/engine.test.ts]: how about:
```
expect(match.exception).to.satisfy(e => e.isGenericHide());
expect(match.exception).to.satisfy(e => (e as NetworkFilter).isException());
```

File: packages/adblocker/src/engine/engine.ts (hunk 1 above)
Comment (chrmod) [reply packages/adblocker/src/engine/engine.ts:1190]: cannot we do:
```
matches: {
  filter: CosmeticFilter | undefined;
  exception: CosmeticFilter | NetworkFilter | undefined;
}[];
```

File: packages/adblocker/src/engine/engine.ts [hunk 5]
```diff
@@ -1214,12 +1234,24 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
...
+    if (specificHideException === undefined) {
+      specificHideException = shouldApplyHideException(specificHides);
+    }
+
+    if (genericHideException !== undefined) {
+      matches.push({
+        filter: undefined,
+        exception: genericHideException,
+      });
+    } else if (specificHideException !== undefined) {
```
Comment (chrmod) [inline packages/adblocker/src/engine/engine.ts]: cannot we have both? 

we can push the match directly after we get return value from  shouldApplyHideException.

eg.
```js
if (genericHideException === undefined) {
  genericHideException = shouldApplyHideException(genericHides);
  if (genericHideException !== undefined) {
    matches.push({ filter: undefined, exception: genericHideException });
  }
}

```

File: packages/adblocker/src/engine/engine.ts [hunk 6]
```diff
@@ -1174,16 +1178,32 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
...
+          exception: NetworkFilter | undefined;
+        }
+    )[];
     allowGenericHides: boolean;
   } {
     domain ||= '';
 
-    let allowGenericHides = true;
-    let allowSpecificHides = true;
+    const matches: (
```
Comment (chrmod) [inline packages/adblocker/src/engine/engine.ts]: cannot we copy `matchCosmeticFilters` return type?

**Review by chrmod — CHANGES_REQUESTED** [review]

File: packages/adblocker/src/engine/engine.ts (hunk 5 above)
Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts]: It has to be a separate if statement as its purpose is to report the existence of `genericHideException`.

Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts]: For priorities, there's no priority between `genericHideException` and `specificHideException` but whatever comes first from the filters' bucket. I just made Engine to report both in ad999a53beef7f60eb78fa1547bb1d6441455e07.

File: packages/adblocker/test/engine/engine.test.ts (hunk 4 above)
Comment (seia-soto) [reply packages/adblocker/test/engine/engine.test.ts]: addressed in ad999a53beef7f60eb78fa1547bb1d6441455e07

File: packages/adblocker/test/engine/engine.test.ts (hunk 3 above)
Comment (seia-soto) [reply packages/adblocker/test/engine/engine.test.ts]: addressed in ad999a53beef7f60eb78fa1547bb1d6441455e07

File: packages/adblocker/test/engine/engine.test.ts (hunk 2 above)
Comment (seia-soto) [reply packages/adblocker/test/engine/engine.test.ts]: addressed in ad999a53beef7f60eb78fa1547bb1d6441455e07

File: packages/adblocker/src/engine/engine.ts (hunk 6 above)
Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts]: addressed in 7c8ad003c74ffa38081b477dd579ab144dc49983

File: packages/adblocker/src/engine/engine.ts (hunk 1 above)
Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts:1190]: I prefer to have explicit typing as there's only two cases that generates `undefined` in `filter`. Also, I believe it's beneficial to allow TypeScript automatically infer if `exception` is `NetworkFilter` or `CosmeticFilter` by checking if `filter` is `undefined`.

File: packages/adblocker/test/engine/engine.test.ts [hunk 7]
```diff
@@ -1825,9 +1828,34 @@ foo.com###selector
...
+      `);
+      const { matches } = engine.matchCosmeticFilters({
+        url: 'https://foo.com',
+        hostname: 'foo.com',
+        domain: 'foo.com',
+        classes: ['ad'],
+        getRulesFromDOM: true,
+      });
+      expect(matches.length).to.be.eql(2);
+      for (const match of matches) {
```
Comment (chrmod) [inline packages/adblocker/test/engine/engine.test.ts]: can we avoid the loop please?

File: packages/adblocker/src/engine/engine.ts (hunk 1 above)
Comment (chrmod) [reply packages/adblocker/src/engine/engine.ts:1190]: but then should the first option require `filter` to be a `CosmeticFilter`? currently you allow undefined

File: packages/adblocker/src/engine/engine.ts [hunk 8]
```diff
@@ -1202,8 +1213,8 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
     const specificHides: NetworkFilter[] = [];
     for (const filter of exceptions) {
       if (filter.isElemHide()) {
-        allowGenericHides = false;
-        allowSpecificHides = false;
+        genericHideException = filter;
```
Comment (chrmod) [inline packages/adblocker/src/engine/engine.ts]: not sure if I understand that. Can you give example of such filter?

shouldn't those filters be tested with `shouldApplyHideException`?

File: packages/adblocker/src/engine/engine.ts [hunk 9]
```diff
@@ -1202,8 +1213,8 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
...
+        specificHideException = filter;
```
Comment (chrmod) [inline packages/adblocker/src/engine/engine.ts]: also, shouldn't those be pushed to matches?

Comment (chrmod) [reply packages/adblocker/src/engine/engine.ts]: please add a test for it

File: packages/adblocker/src/engine/engine.ts (hunk 1 above)
Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts:1190]: addressed by 3cf4a69b48547ef2f31f2a575bdb7d94427b3634

File: packages/adblocker/test/engine/engine.test.ts (hunk 7 above)
Comment (seia-soto) [reply packages/adblocker/test/engine/engine.test.ts]: addressed by 17cb2dbf8824b17326325a9f2e9f5adf222d452c

File: packages/adblocker/src/engine/engine.ts (hunk 8 above)
Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts]: See `$elemhide` from https://adblockplus.org/filter-cheatsheet. It's a different kind.

File: packages/adblocker/src/engine/engine.ts (hunk 9 above)
Comment (seia-soto) [reply packages/adblocker/src/engine/engine.ts]: Those are pushed to matches already.

**Review by chrmod — APPROVED** [review]

File: packages/adblocker/src/engine/engine.ts [hunk 10]
```diff
@@ -40,14 +40,14 @@ import { IPattern } from './metadata/patterns.js';
 
 export const ENGINE_VERSION = 811;
 
-function shouldApplyHideException(filters: NetworkFilter[]): boolean {
+function shouldApplyHideException(filters: NetworkFilter[]): NetworkFilter | undefined {
```
Comment (philipp-classen) [inline packages/adblocker/src/engine/engine.ts]: Since it is no longer a predicate, we could change the name.

Instead of "shouldApplyHideException" something else. Maybe "findHideException" or "findHideFilter" or something like that?

File: packages/adblocker/src/engine/engine.ts [hunk 11]
```diff
@@ -1201,25 +1209,34 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
     const genericHides: NetworkFilter[] = [];
     const specificHides: NetworkFilter[] = [];
     for (const filter of exceptions) {
-      if (filter.isElemHide()) {
-        allowGenericHides = false;
-        allowSpecificHides = false;
-        break;
-      }
-
+      // $elemhide is expressed as both ghide and shide enabled together
```
Comment (philipp-classen) [inline packages/adblocker/src/engine/engine.ts]: Not saying that this section is wrong, but I have a hard time to understand it. At first, it looks counter-intuitive that a filter can be both specific (applying non-globally, but to specific domains only) and generic (applying on all domains).

As I understand, this was also the assumption in the old code. From the new comment, it is explaining that "$elemhide" is both (specific and generic), even though in the old code is was rather the opposite. Also it is not clear to me what "$elemhide" is. Maybe we can clarify this section a bit?

File: packages/adblocker/src/engine/engine.ts [hunk 12]
```diff
@@ -1201,25 +1209,35 @@ export default class FilterEngine extends EventEmitter<EngineEventHandlers> {
...
     const specificHides: NetworkFilter[] = [];
     for (const filter of exceptions) {
-      if (filter.isElemHide()) {
-        allowGenericHides = false;
-        allowSpecificHides = false;
-        break;
-      }
-
+      // A filter is classified as $elemhide when bits for $ghide and $shide are both enabled.
+      // $elemhide is treated as both $ghide and $shide here to calculate the priority later on.
```
Comment (philipp-classen) [inline packages/adblocker/src/engine/engine.ts]: Maybe that here (if you think it is still correct)?

> A filter can be both specific ($shide) and generic ($ghide). In that case, it is an $elemhide, and we have to consider both cases here to calculate the priority later on.

File: packages/adblocker/test/engine/engine.test.ts [hunk 13]
```diff
@@ -1814,6 +1814,74 @@ foo.com###selector
...
+    it('reports generic hide exception', () => {
+      const engine = FilterEngine.parse(`
+        ###ad
+        @@||foo.com^$generichide
+      `);
+      const { matches } = engine.matchCosmeticFilters({
+        url: 'https://foo.com',
+        hostname: 'foo.com',
+        domain: 'foo.com',
+        classes: ['ad'],
```
Comment (chrmod) [inline packages/adblocker/test/engine/engine.test.ts]: this should be `ids`, in all tests

**Review by philipp-classen — APPROVED** [review]
