### PR TITLE
fix: properly find the filter options index

### LINKED ISSUE #3885: Failures on options parsing if a filter has `$` character later than actual options index
### Internals

```
||www.youtube.com/playlist?list=$xhr,1p,replace=/("trackingParam":"kx_fmPxhoPZR)[-_0-9A-Za-z]{150}[-_0-9A-Za-z]+?([-_0-9A-Za-z]{55}lLKPQ-SS"\})/\$1\$2/
```

The above filter has a dollar sign later than actual options index. This causes the internal logic to confuse where is actual options index is:

```ts
// filters/network.ts
// filter$options == Options
// ^     ^
// |     |
// |     optionsIndex
// filterIndexStart
const optionsIndex: number = line.lastIndexOf('$');
```

The following REPL shows how the logic failed:

```cmd
C:\Users\aa\local\repos\adblocker\packages\adblocker>node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> const filter = String.raw`||www.youtube.com/playlist?list=$xhr,1p,replace=/("trackingParam":"kx_fmPxhoPZR)[-_0-9A-Za-z]{150}[-_0-9A-Za-z]+?([-_0-9A-Za-z]{55}lLKPQ-SS"\})/\$1\$2/`;
undefined
> filter.lastIndexOf('$')
148
> filter.slice(filter.lastIndexOf('$') + 1)
'2/
```

### PR DESCRIPTION
**Pull request by seia-soto**
fixes #3885

### CODE REVIEW

File: packages/adblocker/src/filters/network.ts
Comment (remusao) [inline packages/adblocker/src/filters/network.ts:1]: Let's add some tests for this please.

Comment (remusao) [reply packages/adblocker/src/filters/network.ts:1]: You could add tests on NetworkFilter.parse with filters where this new logic matters to be correct?

Comment (remusao) [reply packages/adblocker/src/filters/network.ts:1]: Also this function can be exported from the file without being exposed as a public API of the library. As long as it’s not exported [here](https://github.com/ghostery/adblocker/blob/7c8dbc745dae81951c1b5d8fd22975ee104deb66/packages/adblocker/adblocker.ts#L22) then it’s internal only.

Comment (seia-soto) [reply packages/adblocker/src/filters/network.ts:1]: I thought that the `$replace` should be fine for the test but it's not supported by the library yet. I tried to find out the options can include dollar signs later than the options index but I couldn't find one so far.

File: packages/adblocker/src/filters/network.ts [hunk 1]
```diff
@@ -400,6 +400,20 @@ function compileRegex(
...
 }
 
+function findLastIndexOfUnescapedCharacter(text: string, character: string) {
+  let lastIndex = text.lastIndexOf(character);
+
+  if (lastIndex === -1) {
+    return -1;
+  }
+
+  while (text.charCodeAt(lastIndex - 1) === 92 /* '\\' */) {
```
Comment (remusao) [inline packages/adblocker/src/filters/network.ts:410]: Nit. We need to check that « lastIndex » is not equal to 0 here.

File: packages/adblocker/src/filters/network.ts
Comment (seia-soto) [reply packages/adblocker/src/filters/network.ts:1]: I'll make a separate test for this then.

File: packages/adblocker/src/filters/network.ts [hunk 2]
```diff
@@ -400,6 +400,20 @@ function compileRegex(
...
+    lastIndex = text.slice(0, lastIndex).lastIndexOf(character);
```
Comment (remusao) [inline packages/adblocker/src/filters/network.ts:411]: Isn’t it possible to do something like: text.lastIndexOf(character, lastIndex - 1) in order to avoid slicing.

File: packages/adblocker/src/filters/network.ts (hunk 1 above)
Comment (seia-soto) [reply packages/adblocker/src/filters/network.ts:410]: If the `lastIndex` is zero, it means there's no escape character before the character. We don't need to check if the variable is set to zero.

File: packages/adblocker/src/filters/network.ts (hunk 2 above)
Comment (seia-soto) [reply packages/adblocker/src/filters/network.ts]: Sorry, it should be better definitely. I wasn't aware of the position argument difference compared to `indexOf`.

**Comment by seia-soto** [comment]
Just a note: the test cases added from this PR should be converted and merged to #3886 which was the original purpose. Therefore, the internal export will be removed in the future.

File: packages/adblocker/src/filters/network.ts (hunk 1 above)
Comment (remusao) [reply packages/adblocker/src/filters/network.ts:410]: Yes but your `chatCodeAt` will be out of bound in that case and that should be avoided IMO.

Comment (seia-soto) [reply packages/adblocker/src/filters/network.ts]: It won't throw an exception because it'll return `NaN` in that case. For example:
```
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> ''.charCodeAt(-1)
NaN
> .exit
```

But your way should be safer. I updated the code. Thanks.

File: packages/adblocker/src/filters/network.ts [hunk 3]
```diff
@@ -400,6 +400,20 @@ function compileRegex(
...
 }
 
+export function findLastIndexOfUnescapedCharacter(text: string, character: string) {
+  let lastIndex = text.lastIndexOf(character);
+
+  if (lastIndex === -1) {
+    return -1;
+  }
+
+  while (lastIndex >= 0 && text.charCodeAt(lastIndex - 1) === 92 /* '\\' */) {
```
Comment (remusao) [inline packages/adblocker/src/filters/network.ts:410]: Nit. If `lastIndex` is 0 then we probably want to exit the loop.
```suggestion
  while (lastIndex > 0 && text.charCodeAt(lastIndex - 1) === 92 /* '\\' */) {
```

**Review by chrmod — APPROVED** [review]
