### PR TITLE
packages: adblocker-electron{-preload}: make use of `executeJavaScript`

### LINKED ISSUE #4234: [adblocker-electron] fails to inject scriptlet due to CSP issue
Regression of #3819

- This has started failing again around August 10, it effects Reddit, X, YouTube, and Instagram
- You can still use the [original example repo](https://github.com/spikecodes/electron-adblock-test/) to reproduce it 
- You must reload a few seconds after initial boot to ensure lists are loaded
- You can upgrade the packages to the latest and it still seems to fail
- Could we prioritize gracefully failing vs. fixing this bug? A white-out screen is pretty alarming to my users 😄

```js
// @cliqz/adblocker-electron-preload/index.js
function insertNode(node, document) {
  const parent = document.head || document.documentElement || document;
  if (parent !== null) {
    parent.appendChild(node); // this CSP violation can not be caught by try/catch, hence the crash (blank page)
  }
}
```

### PR DESCRIPTION
**Pull request by nullptropy**
Use `WebContents.executeJavaScript` for adblocker script injection.

Preload script injection is subject to CSP, breaking functionality on some websites.
This change uses `executeJavaScript` API to bypass CSP:

- Replace preload injection with IPC to main process
- Add `adblocker-inject-script` handler in main process
- Throw an error in the renderer process if the injected script fails

Fixes #4234

### CODE REVIEW

**Review by chrmod — APPROVED** [review]

File: packages/adblocker-electron-preload/src/index.ts [hunk 1]
```diff
@@ -56,7 +59,9 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
     const scripts = getCosmeticsFiltersFirst();
     if (scripts) {
       for (const script of scripts) {
-        injectScript(script, document);
+        const result: ScriptInjectionResult = await ipcRenderer.invoke('adblocker-inject-script', script)
```
Comment (seia-soto) [inline packages/adblocker-electron-preload/src/index.ts:62]: This is a huge security risk to the library since this code may expose a chance for website to inject arbitrary script: https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations

Comment (seia-soto) [reply packages/adblocker-electron-preload/src/index.ts:62]: I think we shouldn't pass any script to the backend. Instead, the whole query and execution process should be done on the backend for the security.

**Review by seia-soto — CHANGES_REQUESTED** [review]

File: packages/adblocker-electron-preload/src/index.ts (hunk 1 above)
Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts:62]: Thank you for catching this. I put together this patch with our security model in mind, where we set `sandbox: true`, `contextIsolation: true`, and `nodeIntegration: false`, so this wasn't a problem. I'll address the general case by moving the script execution to the main world completely.

**Review by chrmod — COMMENTED** [review]
can we inject scriplets directly from `get-cosmetic-filters-first` handler?

this will avoid unnecessary communication as what is happening here is:
* 1. preload requests scriptlets by `get-cosmetic-filters-first`
* 2. background matches the scritlets and sends it back to preload
* 3. preload sends scriptlets back to background to perform the injection with `adblocker-inject-script`
* 4. background injects scripts in the main world

We can avoid steps 2 and 3, but injecting the scriptlets directly in the step 1.

**Comment by nullptropy** [comment]
@seia-soto @chrmod I tried to streamline the implementation and fix the issues, please take another look at the patch.

File: packages/adblocker-electron-preload/src/index.ts [hunk 2]
```diff
@@ -7,24 +7,20 @@
...
-  ipcRenderer.send('get-cosmetic-filters', window.location.href, data);
+
+function injectCosmeticFilters(data?: Omit<IBackgroundCallback, 'lifecycle'>): Promise<CosmeticFiltersResponse> {
+  return ipcRenderer.invoke('inject-cosmetic-filters', window.location.href, data);
 }
 
-if (window === window.top && window.location.href.startsWith('devtools://') === false) {
-  (() => {
-    const enableMutationObserver = ipcRenderer.sendSync('is-mutation-observer-enabled');
+if (window === window.top && !window.location.href.startsWith('devtools://')) {
```
Comment (seia-soto) [inline packages/adblocker-electron-preload/src/index.ts:21]: This change is not required, please revert this back to `window === window.top && window.location.href.startsWith('devtools://') === false`. I don't feel the problem but this is just our internal preference to make things more explicit. 👍

File: packages/adblocker-electron/src/index.ts [hunk 3]
```diff
@@ -164,101 +158,65 @@ export class ElectronBlocker extends FiltersEngine {
...
+      ids: msg?.ids,
+
+      // Rules to fetch: true for initial call, false for updates
+      getBaseRules: !msg,
+      getInjectionRules: !msg,
+      getExtendedRules: !msg,
+      getRulesFromHostname: !msg,
+
+      // Only true for update calls when we have DOM information
+      getRulesFromDOM: !!msg,
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:192]: I'd prefer adding a dedicated variable for `!msg`:

```ts
    // `msg` is undefined for the initial call and present for subsequent updates
		const isFirstQuery = msg === undefined
```

I don't know what would be the best variable name for this but the followings can be candidates: `isInitialQuery`, `isFirstRequest`, `isInitialRequest`.

File: packages/adblocker-electron/src/index.ts [hunk 4]
```diff
@@ -164,101 +158,65 @@ export class ElectronBlocker extends FiltersEngine {
...
-      },
-    });
+      if (extended.length > 0) { }
 
-    if (active === false) {
-      return;
+      return { active: true };
+    } catch (error) {
+      return { active: true, error: String(error) };
     }
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:219]: Here, I wonder we can call promises in parallel instead by using `Promise.allSettled`. In our another repository: `ghostery/ghostery-extension`, we don't wait these: https://github.com/ghostery/ghostery-extension/blob/main/extension-manifest-v3/src/background/adblocker.js#L313

File: packages/adblocker-electron/src/index.ts [hunk 5]
```diff
@@ -164,101 +158,65 @@ export class ElectronBlocker extends FiltersEngine {
...
+      getExtendedRules: !msg,
+      getRulesFromHostname: !msg,
+
+      // Only true for update calls when we have DOM information
+      getRulesFromDOM: !!msg,
 
       callerContext: {
         frameId: event.frameId,
         processId: event.processId,
+        lifecycle: msg?.lifecycle,
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:197]: If you have a nice use-case to this addition to the caller context, please let us know. It'll help our future direction in the implementation. The caller context declarations you can see in many places were added to help debugging.

File: packages/adblocker-electron/src/index.ts [hunk 6]
```diff
@@ -164,101 +158,65 @@ export class ElectronBlocker extends FiltersEngine {
   // ElectronBlocker-specific additions to FiltersEngine
   // ----------------------------------------------------------------------- //
 
-  public onIsMutationObserverEnabled = (event: Electron.IpcMainEvent): void => {
-    event.returnValue = this.config.enableMutationObserver;
+  public onIsMutationObserverEnabled = async (_: Electron.IpcMainInvokeEvent): Promise<boolean> => {
+    return this.config.enableMutationObserver;
   };
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:163]: Does this need to be `async`?

File: packages/adblocker-electron-preload/src/index.ts [hunk 7]
```diff
@@ -7,24 +7,20 @@
...
-  return ipcRenderer.sendSync('get-cosmetic-filters-first', window.location.href);
+interface CosmeticFiltersResponse {
+  active: boolean;
+  error?: string;
 }
-function getCosmeticsFiltersUpdate(data: Omit<IBackgroundCallback, 'lifecycle'>) {
-  ipcRenderer.send('get-cosmetic-filters', window.location.href, data);
+
+function injectCosmeticFilters(data?: Omit<IBackgroundCallback, 'lifecycle'>): Promise<CosmeticFiltersResponse> {
+  return ipcRenderer.invoke('inject-cosmetic-filters', window.location.href, data);
```
Comment (seia-soto) [inline packages/adblocker-electron-preload/src/index.ts:18]: Just a dedicated question besides the core functionality: did you suffer from any problems because of event/handler names without namespacing: e.g. prefixing event names with `adblocker-`. If you think you'll see problems because of event names used in adblocker library, I think prefixing event names is totally fine as it's internal details.

File: packages/adblocker-electron-preload/src/index.ts [hunk 8]
```diff
@@ -7,24 +7,20 @@
...
 }
 
-if (window === window.top && window.location.href.startsWith('devtools://') === false) {
-  (() => {
-    const enableMutationObserver = ipcRenderer.sendSync('is-mutation-observer-enabled');
+if (window === window.top && !window.location.href.startsWith('devtools://')) {
+  (async () => {
+    const enableMutationObserver = await ipcRenderer.invoke('is-mutation-observer-enabled');
```
Comment (seia-soto) [inline packages/adblocker-electron-preload/src/index.ts:23]: I won't pick this as a problem but the behavior here slightly changed. @remusao Would it be a problem if we initialise `DOMMonitor` after getting a response from ipc main (the background node script)?

File: packages/adblocker-electron/src/index.ts [hunk 9]
```diff
@@ -58,40 +55,36 @@ export class BlockingContext {
...
-    event: Electron.IpcMainEvent,
+  private readonly onInjectCosmeticFilters: (
+    event: Electron.IpcMainInvokeEvent,
     url: string,
-    msg: IBackgroundCallback,
-  ) => void;
-
-  private readonly onGetCosmeticFiltersFirst: (event: Electron.IpcMainEvent, url: string) => void;
+    msg?: IBackgroundCallback,
+  ) => Promise<{ active: boolean; error?: string }>;
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:62]: We can reuse `CosmeticFiltersResponse` here: `Promise<CosmeticFiltersResponse>`

File: packages/adblocker-electron/src/index.ts [hunk 10]
```diff
@@ -164,101 +158,65 @@ export class ElectronBlocker extends FiltersEngine {
...
+    return this.config.enableMutationObserver;
   };
 
-  public onGetCosmeticFiltersFirst = (event: Electron.IpcMainEvent, url: string) => {
-    // Extract hostname from sender's URL
+  public onInjectCosmeticFilters = async (
+    event: Electron.IpcMainInvokeEvent,
+    url: string,
+    msg?: IBackgroundCallback,
+  ): Promise<{ active: boolean; error?: string }> => {
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:169]: We can reuse `CosmeticFiltersResponse` here: `Promise<CosmeticFiltersResponse>`

File: packages/adblocker-electron/src/index.ts [hunk 11]
```diff
@@ -164,101 +158,65 @@ export class ElectronBlocker extends FiltersEngine {
...
-        frameId: event.frameId,
-        processId: event.processId,
+      for (const script of scripts) {
+        await event.sender.executeJavaScript(script, true);
+      }
 
-        lifecycle: msg.lifecycle,
-      },
-    });
+      if (extended.length > 0) { }
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:214]: From the original code (before this PR), I found that we don't support extended CSS for electron. Let's disable it from match call for now.

File: packages/adblocker-electron-preload/src/index.ts (hunk 8 above)
Comment (seia-soto) [reply packages/adblocker-electron-preload/src/index.ts:23]: Sorry, I think I confused this with `ACTIVE`. I'm closing this review.

File: packages/adblocker-electron-preload/src/index.ts [hunk 12]
```diff
@@ -68,11 +44,11 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
...
       () => {
-        DOM_MONITOR = new DOMMonitor((update) => {
+        DOM_MONITOR = new DOMMonitor(async (update) => {
           if (update.type === 'features') {
-            getCosmeticsFiltersUpdate({
-              ...update,
-            });
+            const response = await injectCosmeticFilters();
+            if (response.error) throw new Error(`error injecting updated cosmetic filters: ${response.error}`)
+            if (!(ACTIVE = response.active)) unload();
```
Comment (seia-soto) [inline packages/adblocker-electron-preload/src/index.ts:51]: Do we want to do unloading here? I don't think we need to unload the dom monitor.

Comment (seia-soto) [reply packages/adblocker-electron-preload/src/index.ts:51]: `active` from `FiltersEngine.getCosmeticFilters` means that if we want cosmetic filters or not. This code will not be reached at all.

```ts
    if (this.config.loadCosmeticFilters === false) {
      return {
        active: false,
        extended: [],
        scripts: [],
        styles: '',
      };
    }
```

**Review by seia-soto — CHANGES_REQUESTED** [review]
Thank you for the contribution. I found some headrooms to improve, but I really appreciate introducing the changes.

File: packages/adblocker-electron/src/index.ts (hunk 3 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts:192]: Makes perfect sense, named the variable `isFirstRun`.

File: packages/adblocker-electron-preload/src/index.ts (hunk 7 above)
Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts]: We've didn't run into issues with this, but I can totally see people getting confused because of clashing IPC handlers, I'll prefix the event handlers with `@ghostery/adblocker/` to make this less likely.

File: packages/adblocker-electron/src/index.ts (hunk 6 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts]: The function needs to return a `Promise`, and the `async` keyword wraps the body in a promise automatically here.

File: packages/adblocker-electron/src/index.ts (hunk 5 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts:209]: Nothing off the top of my head right now, but I'll keep this in mind.

File: packages/adblocker-electron/src/index.ts (hunk 4 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts]: Revised the function behaviour here.

**Comment by nullptropy** [comment]
@seia-soto Thank you for the review! PTAL.

File: packages/adblocker-electron-preload/src/index.ts (hunk 7 above)
Comment (seia-soto) [reply packages/adblocker-electron-preload/src/index.ts]: I think that's a great idea. Thanks for the collaboration.

File: packages/adblocker-electron/src/index.ts (hunk 6 above)
Comment (seia-soto) [reply packages/adblocker-electron/src/index.ts]: Makes sense. Thanks.

File: packages/adblocker-electron/src/index.ts [hunk 13]
```diff
@@ -164,101 +166,80 @@ export class ElectronBlocker extends FiltersEngine {
...
 
-      // Only done on first load in the frame, disable for updates
-      getBaseRules: false,
-      getInjectionRules: false,
-      getExtendedRules: false,
-      getRulesFromHostname: false,
+      // Rules to fetch: true for initial call, false for updates
+      getBaseRules: isFirstRun,
+      getInjectionRules: isFirstRun,
+      getExtendedRules: isFirstRun,
```
Comment (seia-soto) [inline packages/adblocker-electron/src/index.ts:200]: Please, set this as `false` not to query extended rules.

**Comment by seia-soto** [comment]
I found that we were missing tests from adblocker library from https://github.com/ghostery/adblocker/pull/4302 but this PR doesn't have any relationship with that. Therefore, I think it's fine to continue without additional rebasing.

File: packages/adblocker-electron-preload/src/index.ts [hunk 14]
```diff
@@ -68,11 +53,11 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
     window.addEventListener(
       'DOMContentLoaded',
       () => {
-        DOM_MONITOR = new DOMMonitor((update) => {
+        DOM_MONITOR = new DOMMonitor(async (update) => {
```
Comment (philipp-classen) [inline packages/adblocker-electron-preload/src/index.ts:56]: Regarding the error handling: since it is now async, the callback will return a promise. I wonder if this is a problem if the callback failed? From what I see, the caller (DOMMonitor) of the callback does not await the result. It would not see the error, nor wait for the processing here to be completed.

Maybe I'm missing something, but I assume the DOMMonitor is that class here: https://github.com/ghostery/adblocker/blob/40a4c8ba9e738b312284cddc6705b5b2a85864d8/packages/adblocker-content/src/index.ts#L176

File: packages/adblocker-electron-preload/src/index.ts [hunk 15]
```diff
@@ -7,24 +7,28 @@
...
+    window.location.href,
+    data,
+  );
 }
 
 if (window === window.top && window.location.href.startsWith('devtools://') === false) {
-  (() => {
-    const enableMutationObserver = ipcRenderer.sendSync('is-mutation-observer-enabled');
+  (async () => {
+    const enableMutationObserver = await ipcRenderer.invoke(
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:29]: turning this to async may introduce a noticable delay. 

What is the reason to avoid `ipcRenderer.sendSync`?

File: packages/adblocker-electron-preload/src/index.ts [hunk 16]
```diff
@@ -7,24 +7,28 @@
...
+    '@ghostery/adblocker/inject-cosmetic-filters',
+    window.location.href,
+    data,
+  );
 }
 
 if (window === window.top && window.location.href.startsWith('devtools://') === false) {
-  (() => {
-    const enableMutationObserver = ipcRenderer.sendSync('is-mutation-observer-enabled');
+  (async () => {
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:28]: Not sure if there is a strong reason to make this async. 
For the `injectCosmeticFilters` you can use regular `then`.

File: packages/adblocker-electron-preload/src/index.ts (hunk 14 above)
Comment (chrmod) [reply packages/adblocker-electron-preload/src/index.ts:56]: exactly - DOMMonitor relay on the fact the the it callback will execute sync. It is not only about error handling, but for example for `handleNewFeatures` which from what I see assumes the DOM was affected.

File: packages/adblocker-electron/src/index.ts [hunk 17]
```diff
@@ -164,101 +166,80 @@ export class ElectronBlocker extends FiltersEngine {
...
+      return { active: false };
     }
 
-    // Inject custom stylesheets
-    this.injectStyles(event.sender, styles);
+    if (styles.length > 0) {
+      try {
+        await event.sender.insertCSS(styles, { cssOrigin: 'user' });
+      } catch (error) {
+        return {
```
Comment (chrmod) [inline packages/adblocker-electron/src/index.ts:221]: this is a problem - if you fail to inject CSS, you don't try to inject scriptlets

File: packages/adblocker-electron/src/index.ts [hunk 18]
```diff
@@ -164,101 +166,80 @@ export class ElectronBlocker extends FiltersEngine {
...
+          active: false,
+          error: `CSS insertion failed: ${error instanceof Error ? error.message : String(error)}`,
+        };
+      }
+    }
+
+    const scriptResults = await Promise.allSettled(
+      scripts.map((script) => event.sender.executeJavaScript(script, true)),
+    );
```
Comment (chrmod) [inline packages/adblocker-electron/src/index.ts:230]: how about combining all scriptlets into a single script so we can inject all at once?

**Review by chrmod — CHANGES_REQUESTED** [review]
Thank you very much for pushing this forward. It is clear that electron deserves improvements. 

This review may take a bit more time as the entire team is catching up with electron changes and we want to be sure we can get most out of your efforts, so please bear with us :)

Was thinking, how about instead of requesting scriptlets from the `preload` script, we push them directly based on [did-navigate](https://www.electronjs.org/docs/latest/api/web-contents#event-did-navigate) and [did-frame-navigate](https://www.electronjs.org/docs/latest/api/web-contents#event-did-frame-navigate) which would make it closer to the way the Ghostery extension does the [scritplet injection](https://github.com/ghostery/ghostery-extension/blob/7da14846035cd3c3e71319f8f25e91c18ea9715e/extension-manifest-v3/src/background/adblocker.js#L422)

With that approach, changes to the other cosmetic filters injection could be minimal.

File: packages/adblocker-electron-preload/src/index.ts (hunk 15 above)
Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts:29]: This will block the renderer until the call is resolved. Definitely not something we would want in our product. Electron itself does suggest to move away from `sendSync` to `invoke` [0].

[0] https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrenderersendsyncchannel-args

Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts:29]: > turning this to async may introduce a noticable delay.

My understanding of async JavaScript doesn't suggest this. Please correct me if I'm wrong.

File: packages/adblocker-electron-preload/src/index.ts (hunk 16 above)
Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts:28]: I did a general API overhaul to switch to using `invoke` in general. This is a much more modern and overall better approach. Please correct me if I'm wrong.

File: packages/adblocker-electron/src/index.ts (hunk 17 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts:221]: I'll address this, thank you for catching it.

File: packages/adblocker-electron/src/index.ts (hunk 18 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts:230]: I'd suggest we create another ticket for this once we merge the changes here. I'd like to keep the scope to fixing #4234.

File: packages/adblocker-electron-preload/src/index.ts (hunk 14 above)
Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts:56]: I'll think of a way to address this, thank you for catching it!

**Comment by nullptropy** [comment]
Thank you for the review @chrmod! I've replied most of the comments, and I think the most important one to address is that `DOMUpdater` expects a sync function.

I’d prefer to handle broader changes in other PRs since the electron package isn't fully functional right now. We rely on `@ghostery/adblocker-electron` in our product, so we'll definitely be here to help maintain the project as issues arise.

File: packages/adblocker-electron-preload/src/index.ts [hunk 19]
```diff
@@ -68,11 +53,11 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
...
       () => {
-        DOM_MONITOR = new DOMMonitor((update) => {
+        DOM_MONITOR = new DOMMonitor(async (update) => {
           if (update.type === 'features') {
-            getCosmeticsFiltersUpdate({
-              ...update,
-            });
+            const response = await injectCosmeticFilters();
+            if (response.error)
+              throw new Error(`error injecting updated cosmetic filters: ${response.error}`);
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:60]: lets remove the `async` from the function definition, and change this to 

```js
injectCosmeticFilters().then((response) => {
  if (response.error) {
    console.error(`error injecting updated cosmetic filters: ${response.error}`);
  }
});

File: packages/adblocker-electron/src/index.ts (hunk 18 above)
Comment (chrmod) [reply packages/adblocker-electron/src/index.ts:230]: make sense!

File: packages/adblocker-electron-preload/src/index.ts (hunk 15 above)
Comment (chrmod) [reply packages/adblocker-electron-preload/src/index.ts:29]: If this works well in your use-case then we should be good with merging those changes. It is clear that that avoiding blocking of the renderer thread is something beneficial, but we have to be mindful that specifically scriptlet injection is very time sensitive. Some scriptlets have to be injected before the page loads own scripts. Otherwise, some ads wont be blocked.

This is way I strongly suggest to decouple scriplet injection from other cosmetic filter injection as described here https://github.com/ghostery/adblocker/pull/4278#pullrequestreview-2326062789

File: packages/adblocker-electron/src/index.ts (hunk 17 above)
Comment (nullptropy) [reply packages/adblocker-electron/src/index.ts:221]: Seems like we don't need to await on insertCSS, or handle errors, we simply call it and proceed to script injection right now. Please let me know if we should do it in order.

**Comment by nullptropy** [comment]
@chrmod PTAL, updated the branch!

File: packages/adblocker-electron-preload/src/index.ts [hunk 20]
```diff
@@ -68,10 +53,12 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
     window.addEventListener(
       'DOMContentLoaded',
       () => {
-        DOM_MONITOR = new DOMMonitor((update) => {
+        DOM_MONITOR = new DOMMonitor(async (update) => {
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:56]:
```suggestion
        DOM_MONITOR = new DOMMonitor((update) => {
```

File: packages/adblocker-electron-preload/src/index.ts [hunk 21]
```diff
@@ -7,24 +7,28 @@
...
-import {
-  DOMMonitor,
-  IBackgroundCallback,
-  IMessageFromBackground,
-  injectScript,
-} from '@cliqz/adblocker-content';
+type CosmeticFiltersResponse = {
+  active: boolean;
+  error?: string;
+};
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:15]:
```suggestion
interface ICosmeticFiltersResponse = {
  active: boolean;
  error?: string;
};
```
To match the naming convention of `IBackgroundCallback`

**Comment by nullptropy** [comment]
@chrmod Pushed some changes that hopefully addresses the review. I'm losing the thread a bit, please let me know if the changes conform to what you suggested.

File: packages/adblocker-electron-preload/src/index.ts [hunk 22]
```diff
@@ -8,25 +8,22 @@
...
+    window.location.href,
+    data,
+  );
 }
 
 if (window === window.top && window.location.href.startsWith('devtools://') === false) {
-  (() => {
-    const enableMutationObserver = ipcRenderer.sendSync('is-mutation-observer-enabled');
+  (async () => {
+    const enableMutationObserver = await ipcRenderer.invoke(
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:23]: I don't think this is needed. It should be fine to always create the DOM_MONITOR but only start it when needed. With this line removed, the wrapping function can be sync again

File: packages/adblocker-electron/src/index.ts [hunk 23]
```diff
@@ -164,101 +163,63 @@ export class ElectronBlocker extends FiltersEngine {
...
       },
     });
 
     if (active === false) {
       return;
     }
 
-    // Inject custom stylesheets
-    this.injectStyles(event.sender, styles);
+    event.sender.insertCSS(styles, { cssOrigin: 'user' });
```
Comment (chrmod) [inline packages/adblocker-electron/src/index.ts:214]: I guess we should keep the previous check and insertCSS only if there are some styles
```
if (styles.length > 0) {
```

**Review by chrmod — CHANGES_REQUESTED** [review]
I think we need one more change around the async code.

Can you already confirm that this works with youtube.com ads?

**Comment by nullptropy** [comment]
@chrmod Committed the suggestions. I can confirm that this works on `youtube.com`.

File: packages/adblocker-electron-preload/src/index.ts [hunk 24]
```diff
@@ -70,19 +41,17 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
       () => {
         DOM_MONITOR = new DOMMonitor((update) => {
           if (update.type === 'features') {
-            getCosmeticsFiltersUpdate({
-              ...update,
-            });
+            injectCosmeticFilters();
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:44]:
```suggestion
            injectCosmeticFilters({
              ...update,
            });
```

Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:44]:
```suggestion
            injectCosmeticFilters({
               ...update,
            });
```

**Review by chrmod — CHANGES_REQUESTED** [review]
Looks like one last thing is missing - I've made a code suggestion

**Review by seia-soto — APPROVED** [review]

**Review by chrmod — APPROVED** [review]

File: packages/adblocker-electron-preload/src/index.ts [hunk 25]
```diff
@@ -70,8 +41,8 @@ if (window === window.top && window.location.href.startsWith('devtools://') ===
       () => {
         DOM_MONITOR = new DOMMonitor((update) => {
           if (update.type === 'features') {
-            getCosmeticsFiltersUpdate({
-              ...update,
+            injectCosmeticFilters({
+               ...update,
```
Comment (chrmod) [inline packages/adblocker-electron-preload/src/index.ts:45]:
```suggestion
              ...update,
```

Comment (chrmod) [reply packages/adblocker-electron-preload/src/index.ts:45]: this single whitespace breaks the linter

**Review by chrmod — CHANGES_REQUESTED** [review]
This is now merge ready, we only have to fix the linter.

File: packages/adblocker-electron-preload/src/index.ts (hunk 25 above)
Comment (nullptropy) [reply packages/adblocker-electron-preload/src/index.ts]: fixed it, thanks!

**Comment by seia-soto** [comment]
Running CI. 👍

**Comment by seia-soto** [comment]
We would like to extend our sincere appreciation and congratulations to you for your valuable contribution to the adblocker library. We are pleased to merge this fix, which will benefit all users, and we are grateful for the time and effort you invested in addressing this issue.

**Comment by chrmod** [comment]
Many thanks @nullptropy !

**Comment by nullptropy** [comment]
Thanks for being patient with me and for all the hard work you guys put into this library, I really appreciate it! @seia-soto @chrmod

**Comment by PascalPixel** [comment]
wonderful work, thank you for your time and effort (ﾉ´ヮ´)ﾉ*: ･ﾟ
